plugins:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - "vendor/**/*"
    - ".git/**/*"
    - "bin/**/*"
    - "db/schema.rb"
    - "storage/**/*"
    - "tmp/**/*"
    - "public/**/*"
    - "log/**/*"
    - "coverage/**/*"
    - "app/packs/**/*"
  UseCache: true

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

# Layout/LineLength:
#   Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Exclude:
    - "db/**/*.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
    - "config/**/*.rb"

Metrics/MethodLength:
  Exclude:
    - "db/**/*.rb"

RSpec/ExampleLength:
  Exclude:
    - "spec/features/**/*.rb"

RSpec/MultipleMemoizedHelpers:
  Max: 7

RSpec/PendingWithoutReason:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

# Rails/ActionOrder:
#   ExpectedOrder: [index, show, new, create, edit, update, destroy]

Rails/ApplicationRecord:
  Exclude:
    - "db/**/*.rb"

Rails/SkipsModelValidations:
  Exclude:
    - "db/migrate/**/*"

# Style/AsciiComments:
#   Enabled: false

Style/Documentation:
  Enabled: false

Style/QuotedSymbols:
  EnforcedStyle: double_quotes

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: diff_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: diff_comma
