require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rails

AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/seeds.rb'
   - 'db/schema.rb'
   - 'vendor/bundle/**/*'

Rails:
  Enabled: true