require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rails
  # - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - "node_modules/**/*"
    - "vendor/**/*"
    - ".git/**/*"
    - "bin/**/*"
    - "db/schema.rb"
    - "storage/**/*"
    - "tmp/**/*"
    - "public/**/*"
    - "log/**/*"
    - "coverage/**/*"
    - "app/packs/**/*"

Metrics/MethodLength:
  Exclude:
    - "db/**/*.rb"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes